# Generated by Django 4.1 on 2023-03-19 23:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accountsApp', '0002_dailygoal'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailygoal',
            name='mailer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
