# Generated by Django 4.1 on 2023-03-20 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountsApp', '0004_dailygoal_goal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailygoal',
            name='Day',
            field=models.CharField(default='Monday', max_length=30),
        ),
    ]
