# Generated by Django 4.1 on 2023-03-20 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountsApp', '0005_alter_dailygoal_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailygoal',
            name='dayOfMonth',
            field=models.IntegerField(default='20'),
        ),
        migrations.AlterField(
            model_name='dailygoal',
            name='Year',
            field=models.IntegerField(default='2023'),
        ),
    ]
