# Generated by Django 4.1 on 2023-03-20 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountsApp', '0006_dailygoal_dayofmonth_alter_dailygoal_year'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailer',
            options={},
        ),
        migrations.AlterModelTable(
            name='dailygoal',
            table='Goal',
        ),
        migrations.AlterModelTable(
            name='mailer',
            table='Mailer',
        ),
    ]
